### ISSUE TITLE
Understanding the API

### ISSUE THREAD

**Issue by eitch** [SequentMicrosystems/4relay-rpi#4]
The code you've provided is for C, Python, etc. I would like to use it in Java by communicating simply over I2C.

Currently i was able to communicate with the 4relay-rpi by using the simple i2cset and i2cget commands:

    $ i2cset -y 1 0x3f 0x01 0x80
    $ i2cget -y 1 0x3f 0x01

Reading your code i see that you first read some data, then set the I/Os to output. In my simple test this was not necessary. Could you tell me what kind of setup is required? Looking at the TCA9534, it seems similar to a MCP23017, which is something that i have worked with. There setting the I/Os to output is enough, but it seems the TCA9534 has this as default?

Further i see you reading from registers, what is it that you do? 

Thanks for any feedback.
Kind regards

**Comment by alexburcea2877** [comment]
Hi,

The first thing I do is to check if the io-expander was initialized or not, if not, I set the output register to 0 to prevent turning on the relays and set pins as output.
If you run the commands after you run "4relay" once is normal to work because the i/o directions have been previously configured.

Alex

**Comment by eitch** [comment]
Thanks, i was now able to setup my code to properly initialize the TCA9534: https://github.com/strolch-li/strolch-plc/blob/develop/strolch-plc-core/src/main/java/li/strolch/plc/core/hw/i2c/TCA9534OutputConnection.java#L37
